### ISSUE TITLE
damage tools always reduced by only 1 HP?

### ISSUE THREAD

**Issue by denniapr14** [binary404/MysticTools#11]
i am love mystictools mod but i have questions
i am use mystictools-1.16.5-1.4.1.jar, 
attacks from tools such as axes, shovels, and pickaxes always 1 hp
is it a bug or not?
![2021-06-03_21 22 00](https://user-images.githubusercontent.com/58542020/120660788-dfec6880-c4b1-11eb-9a36-89315d85f14b.png)

**Comment by binary404** [comment]
That is intentional.
