### ISSUE TITLE
Crash on using a Mystic Pick, Shovel, or Axe

### ISSUE THREAD

**Issue by IronGem** [binary404/MysticTools#12]
I am not sure if this crash is due to the mod or an incompatibility with the forge version.  Either way, Minecraft crashes anytime I use either a pick, shovel or axe on a block.  The swords seem to work just fine.  Please let me know if you need further details. 

Minecraft: 1.17.1
Forge: 37.0.75 and 37.0.82
MysticTools: 1.17.1 1.0.0

[crash-2021-10-05_15.34.02-server.txt](https://github.com/binary404/MysticTools/files/7289446/crash-2021-10-05_15.34.02-server.txt)

**Comment by binary404** [comment]
Fixed in mystic tools 1.17.1-1.0.1 and mystic tools 1.18-1.0.0/1.18.1-1.0.0
